heat_template_version: 2013-05-23
description: >
  Heat template to deploy EGO services
resources:
  hadc:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      desired_capacity: 1
      max_size: 3
      resource:
        type: IBMInc::EGO::Activity
        properties:
          svc_name: 'hadc'
          description: 'data nodes'
          control_policy: {
            start_type: 'AUTOMATIC',
            max_restarts: 10,
          }
          allocation_specification: {
            consumer_id: '/ManagementServices/EGOManagementServices',
            resource_specification: {
              resource_group: 'ManagementHosts',
              resource_requirement: 'select(!NTIA64 &amp;&amp; !SOL64)',
            }
          }
          activity_description: {
            htype: 'all',
            activity_specification: {
              command: 'sleep 10000',
              job_controller: 'sleep 10000'
            }
          }
  up-policy:
    type: OS::Heat::ScalingPolicy
    properties:
      auto_scaling_group_id: {get_resource: hadc}
      adjustment_type: change_in_capacity
      scaling_adjustment: 1
  down-policy:
    type: OS::Heat::ScalingPolicy
    properties:
      auto_scaling_group_id: {get_resource: hadc}
      adjustment_type: change_in_capacity
      scaling_adjustment: -1
