heat_template_version: 2013-05-23

description: >
  A document-based template to configure your Software Defined Environment.

parameters:
  # declaration of input parameters
  external_network_id:
    type: string
    description: Load Balancer Pool Subnet ID
    default: ac3dd16d9-c201-46f1-b231-03b1f6cc3238
  flavor:
    type: string
    description: Flavor to be used for compute instance
    default: "m1.small"
  image:
    type: string
    description: Image used for servers
    default: lbaas

resources:
  ag_php:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 5
      resource:
        type: IBMInc::EGO::Activity
        properties:
          containers:
            - description: 'web server'
              name: nginx
              image: dockerfile/nginx
              memory: 200m
              cpu: 1
              cmd: cmd1
              ports:
                - containerPort: 8083
                  hostPort: 8083
                - containerPort: 8086
                  hostPort: 8086
              volumeMounts:
                - name: www-data
                  mountPath: /srv/www
                  readOnly: True
            - description: 'git monitor'
              name: git-monitor
              image: kubernetes/git-monitor
              memory: 200m
              cpu: 2
              cmd: cmd2
              env:
                - name: xx
                  value: xx
                - name: xx
                  value: xx
              volumeMounts:
                - name: www-data
                  mountPath: /data
          svc_name: 'www'
          description: 'desc'
          network_id: xxxx
          control_policy:
            host_failover_intervel: 60
            service_failover_fencing: 'LINUXResourceSpeci86'
            service_failover_fencing_wait_period: 120
            dependencies:
              - type: 'OnStart'
                satisfy: 'STARTED'
                keep: 'STARTED'
                autoStart: false
                service: 'service1'
            block_host_exit_values:
              - exit_value: 'a'
              - exit_value: 'b'
          allocation_specification:
            keep_block_host_list: 'host1;host2;'
            resource_specification:
              resource_requirement: 'select(prsdemo3)' ==> need refine
          activity_description:
            htype: 'all'
            log_path: '/tmp/svr.log'
            activity_specification:
              inactivity_period: 60
              cleanup_command: '/opt/biginsights/spark/uninstall.sh'
              cleanup_finish_wait_period: 120
              control_wait_period: 360
              environment_variables:
                - key: 'PATH'
                  value: '/usr/bin;/bin'
                - key: 'HOSTNAME'
                  value: 'host1'
              pre_commands:
                - timeout: 10
                  stdout_file: '/tmp/a'
                  stderr_file: '/tmp/b'
                  cmd: 'sleep 20'
              command: ['/usr/sbin/sshd -D']
              post_commands:
                - timeout: 20
                  stdout_file: '/tmp/c'
                  stderr_file: '/tmp/d'
                  cmd: 'sleep 20'
              job_controller: '/usr/local/jboss/bin/shutdown all'
              job_monitor: '/opt/bin/JobMonitor.sh'
              job_monitor_max_update_interval: 60
              default_url: 'http://${HOSTNAME}:8080/mypath'
              working_dir: '/opt/ibm/ego'
              umask: 0755
