
MAINTAINER Klaus Ma <klaus1982.cn@gmail.com>
MAINTAINER Yong Feng <yongfeng@ca.ibm.com>

RUN mkdir -p /opt/ibm/mesos/work /opt/ibm/mesos/log

ENTRYPOINT ["mesos-master", "--work_dir=/opt/ibm/mesos/work", "--log_dir=/opt/ibm/mesos/log"]
